"""Submit-file rendering for HTCondor."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SubmitConfig:
    executable: str
    arguments: str
    job_list: Path
    queue_vars: list[str]
    transfer_input_files: str = ""
    job_flavour: str = "workday"
    request_cpus: int = 1
    request_memory: str = "4GB"
    request_disk: str = "20GB"
    max_retries: int = 1
    condor_log: str = "condor.log"
    x509userproxy: str = "$ENV(X509_USER_PROXY)"
    transfer_output_files: str = '""'


def render_submit_file(config: SubmitConfig) -> str:
    queue_vars = ",".join(config.queue_vars)
    x509_line = ""
    if config.x509userproxy:
        x509_line = f"x509userproxy           = {config.x509userproxy}\n"

    return f"""# Auto-generated by prepare_condor_jobs.py

executable              = {config.executable}
arguments               = {config.arguments}

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = {config.transfer_input_files}
{x509_line}transfer_output_files   = {config.transfer_output_files}

output                  = $(run_dir)/condor.out
error                   = $(run_dir)/condor.err
log                     = {config.condor_log}

request_cpus            = {config.request_cpus}
request_memory          = {config.request_memory}
request_disk            = {config.request_disk}

+JobFlavour             = "{config.job_flavour}"
max_retries             = {config.max_retries}

queue {queue_vars} from {config.job_list}
"""
